dist: trusty
sudo: false
language: python
python:
- 3.5
env:
  global:
  - secure: avZof6zOvqzTz3HIWKUCCVnNtN1kUJJUulrRPqQNukYpvK6pPFmv9bv0KPZeTWr7fC88fnptjm2SbgXhtNkZxv0pqRP2Zy5yzgwZfQlHJKWb2DSA7D65kCCejHvmyIx6fbpfG4A7OMGHKP1yoUOkgm3WXmXXfckKZ0ADiEnvx1kenhF4MfMNoAxBIX/xX9NtKxWejvF/Go18ePxVW/Y+UpOQ9l8n9z3RZQ2+ocoSP/7RhQTNnJgHO+S9UtnRVN5yBkUTiLU9I7+NpvcLbBekLGyS0Vh979HT0oDU/LAbpXWIfGFm97CY7zn7pCa3vkPtbGs/+FVAo10ZYuLYYrzlxipbrEGPBAQl0eFbIu7Fl/aQWsGYM0/kLiLKFl+/8NgB+eblGb7F8CyUKWgpARlGLc50Ht0C/QBREzRT7bLoDfRxsGc90vQ+mw1D6P7w1vi6Ib3XeVw+zSKvtgb8ul+lqbuShkiH2x4gE+M/1NLByWTIsVdEqiyLK9up+xYOLw7X3swaXLTEjNVTi8havQEABn+cVZPpiOSQcIyF3ydW7kVOqAzc3ewrYPasgOTj2humYTwpAm3Cv49OqahRKA03S7iGzNCzLn1uTX6EsftztCV4OHHHZrsBNB3Kyni/OJh0hg8tc23EXPdBSy2bQFFyeHCG5oyMsy6S+aEZmC08968=
install:
- pip install -r requirements.txt
- cd rug_pygments; python setup.py install; cd ..
script:
- mkdocs build && rm site/CNAME && bash deploy.bash $TRAVIS_REPO_SLUG && cp docs/CNAME site/CNAME
deploy:
  provider: releases
  api_key:
    secure: pyaxQjhyUN2Lr91v2jAbqBCd6G+e91zJvKxvkWRL+DQR0i0mnmUS04iTkB2uEykystixqVKT6XYif/S12NAH03SFFwrgiaSF8hQgNG9l40nLhE00/mnxajezFVp98vwivEs+2CSy8CTRhZw9H3yT6A5ja7dN+t7EyrFs1gfP8VKEoJyrEajkIh8nlELDmoISKcRPUlEqjMUm2Ve/axaQoxbu5JKJcpSJ+X8gwv5bFU0JpFtAZcsxu7KaDFgtujaKavzt+HiXvDgvcawpTzuAdoZBW0hEEbjmAOnbRd5RHpg+1mvbkOdP5Or5bfsrf6ohW994pGSmGi7mNsCB8SV0oEMBeVTVObqoKLAvN5QF49Zm4k95SurGJCDuG/JQbiDWUE203mA4vwZZE5i1FnkqR71U0ufKm1ERu5U6dSh8fQNQShHld+8nscrWb9QC7WTrd4kXVt2ZhexrKV1TYCzspuA12Dr2t/4FC/Pr9vj9nb8f/J53OcrXJvmYJcIxJnbhmK2mbhEYLT4TzoxNJpaucvzhYnV9ojBtNqauS75BtIZlu/mS+Sgq6RZME/7cnGmeQn8pPK3KyGDq2Iiv59JigbI3jcZqMcLiA67W7JR0YTOjTfNVHhf2TqKbaxMOOnlcPYzqA1853gCxoE8ek5QUy3zWehJRQQeumPU72uMt0j8=
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
after_deploy:
- bash deploy.bash atomisthq/atomisthq.github.io master
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
