site_name: The Atomist Documentation
site_description: Documentation for the Atomist Developer Platform
site_author: The Atomist Team
copyright: '&copy; 2017 Atomist, Inc.'
extra:
  main_site_url: https://www.atomist.com/
theme: material
site_favicon: images/favicon.ico
extra:
  logo: images/atomist-logo-horiz-reversed.svg
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: medium
      link: https://the-composition.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
extra_css:
  - stylesheets/extra.css
google_analytics:
  - UA-74966852-1
  - auto
markdown_extensions:
  - markdown_include.include:
      base_path: "docs/common"
  - admonition
  - codehilite(guess_lang=false, linenums=false)
  - def_list
  - footnotes
  - meta
  - smarty
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
repo_name: Rug
repo_url: https://github.com/atomist/rug
pages:
- Introduction: index.md
- Getting Started:
    - Overview: getting-started/index.md
    - Prerequisites: getting-started/prerequisites.md
    - Connect Atomist to Slack: getting-started/slack.md
    - Connect Atomist to GitHub: getting-started/github.md
    - Connect Atomist to CI:
        - Overview: getting-started/ci.md
        - Travis CI: getting-started/travis-ci.md
        - Jenkins: getting-started/jenkins.md
    - Atomist Bot: getting-started/bot.md
    - What next: getting-started/what-next.md
- User Guide:
    - Introduction: user-guide/index.md
    - Interfaces:
        - Introduction: user-guide/interfaces/index.md
        - Bot: user-guide/interfaces/bot.md
        - CLI:
            - Overview: user-guide/interfaces/cli/index.md
            - Installation: user-guide/interfaces/cli/install.md
            - Basics: user-guide/interfaces/cli/basics.md
            - Using Rugs: user-guide/interfaces/cli/using-rugs.md
            - Developing Rugs: user-guide/interfaces/cli/developing-rugs.md
    - Integrations:
        - Overview: user-guide/integrations/index.md
        - Slack: user-guide/integrations/slack.md
        - GitHub.com: user-guide/integrations/github.md
        - Travis CI: user-guide/integrations/travis-ci.md
        - Jenkins: user-guide/integrations/jenkins.md
    - Permissions:
        - Overview: user-guide/permissions/index.md
        - Slack Scopes: user-guide/permissions/slack.md
        - GitHub Scopes: user-guide/permissions/github.md
    - Fingerprints: user-guide/fingerprints.md
    - Spring Agent: user-guide/spring-agent.md
    - Seeds: user-guide/seeds.md
- How To Configure:
    - Introduction: how-to-configure/index.md
- How To Customize:
    - Introduction: how-to-customize/index.md
    - Setup Rug CLI: how-to-customize/setup-cli.md
    - Create Rug Project: how-to-customize/create-rug-project.md
    - Setup TypeScript: how-to-customize/setup-typescript.md
    - Publish Rug Project: how-to-customize/publish-rug-project.md
    - Add Bot Command: how-to-customize/add-bot-command.md
#    - Custom Commit Notifications: tutorials/custom-commit-notifications.md
- Reference Documentation:
    - Overview: 
        - Introduction: reference/index.md
        - Atomist Concepts: reference/platform/concepts.md
        - Atomist Capabilities: reference/platform/capabilities.md
    - Rug:
        - Overview: reference/rug/index.md
        - Event Handlers: reference/rug/event-handlers.md
        - Command Handlers: reference/rug/command-handlers.md
        - Editors: reference/rug/editors.md
        - Generators: reference/rug/generators.md
        - Secrets: reference/rug/secrets.md
        - Projects: reference/rug/projects.md
        - Archives: reference/rug/archives.md
        - Lifecycle: reference/rug/lifecycle.md
        - Runtime: reference/rug/runtime.md
        - Conventions: reference/rug/conventions.md
        - Functions: reference/rug/rug-functions.md
        - Extensions: reference/rug/extensions.md
        - Path Expressions: reference/rug/path-expressions.md
        - Microgrammars: reference/rug/microgrammars.md
        - Templates: reference/rug/templates.md
        - Tests: reference/rug/tests.md
        - Archives: reference/rug/archives.md
    - Rug CLI: reference/rug-cli/index.md
