site_name: Atomist Documentation
site_description: Documentation for Atomist - How Teams Deliver Software
site_author: The Atomist Team
repo_name: GitHub
repo_url: https://github.com/atomist/docs
edit_uri: edit/master/docs/
copyright: "&copy; 2018 Atomist, Inc."
extra:
  main_site_url: https://atomist.com/
  social:
    - type: medium
      link: https://the-composition.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
theme:
  name: material
  favicon: "img/favicon.ico"
  logo: img/atomist-developer-docs-logo.png
  palette:
    primary: white
    accent: teal
  custom_dir: "theme"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/intercom.js
  - js/mixpanel.js
markdown_extensions:
  - markdown_include.include:
      base_path: "common"
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - smarty
repo_url: https://github.com/atomist/docs/
nav:
  - Introduction: index.md
  - Using Atomist:
      - Getting Started: user/index.md
      - Atomist Dashboard: user/dashboard.md
      - Source Control: user/github.md
      - Slack: user/slack.md
      - Built-in Chat Integrations: user/lifecycle.md
      - Supported Integrations: user/integrations.md
  - Developer Quick Start: quick-start.md
  - Developer Guide:
      - What you can do: developer/index.md
      - Architecture: developer/architecture.md
      - Running an SDM:
        - About the SDM: developer/sdm.md
        - Prerequisites: developer/prerequisites.md
        - Team Mode: developer/team.md
        - Local Mode: developer/local.md
        - Adding Functionality: developer/sdm-construct.md
        - Deploying your SDM: developer/sdm-deploy.md
        - Debugging an SDM: developer/sdm-debug.md
      - Goals:
          - Create Goals: developer/goal.md
          - Setting Goals: developer/set-goals.md
          - Registrations: developer/registration.md
      - Builds:
        - Build Goal: developer/build.md
        - Integrations: user/ci.md
        - Reacting to Builds: developer/build-event.md
      - Deploys: developer/deploy.md
      - Code Inspections: developer/inspect.md
      - Code Transforms:
          - Transforms: developer/transform.md
          - Autofixes: developer/autofix.md
          - Project: developer/project.md
      - Commands: developer/commands.md
      - Project Generators: developer/create.md
      - Fingerprints: developer/fingerprint.md
      - Advanced:
         - SDM Concepts: developer/sdm-concepts.md
         - SDM Configuration: developer/config.md
         - Push Tests: developer/push-test.md
         - Generic Builder: developer/spawn-builder.md
         - HTTP Calls in an SDM: developer/http.md
         - Events: developer/events.md
         - Custom GraphQL Queries: developer/graphql.md
         - Chat Messages: developer/slack.md
         - Command Line Interface: developer/cli.md
         - Security Model: developer/security.md
      - Glossary: developer/glossary.md
      - Troubleshooting: developer/troubleshoot.md
  - Extensions:
    - Extension Packs: pack/index.md
    - Build: pack/build.md
    - Spring: pack/spring.md
    - Kubernetes: pack/kubernetes.md
    - Cloud Foundry: pack/pcf.md
    - Node: pack/node.md
    - Sonarqube: pack/sonarqube.md
    - Checkstyle: pack/checkstyle.md
    - Docker: pack/docker.md
    - Lines of Code: pack/sloc.md
    - Changelog: pack/changelog.md
    - Issue: pack/issue.md
  - Support: support.md
