site_name: Atomist Documentation
site_description: Documentation for Atomist - How Teams Deliver Software
site_author: The Atomist Team
copyright: "&copy; 2018 Atomist, Inc."
extra:
  main_site_url: https://atomist.com/
  social:
    - type: medium
      link: https://the-composition.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
theme:
  name: material
  favicon: "img/favicon.ico"
  logo: img/atomist-logo-horiz-reversed.svg
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: "theme"
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/intercom.js
  - js/mixpanel.js
markdown_extensions:
  - markdown_include.include:
      base_path: "docs/common"
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list
  - footnotes
  - meta
  - smarty
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
# repo_name: Atomist Software Delivery Machine
# repo_url: https://github.com/atomist/sdm
pages:
  - Introduction: index.md
  - Using Atomist:
      - Getting Started: user/index.md
      - GitHub: user/github.md
      - Slack: user/slack.md
      - Continuous Integration: user/ci.md
      - Kubernetes: user/kubernetes.md
  - Developer Quick Start: quick-start.md
  - Developer Guide:
      - Overview: developer/index.md
      - Prerequisites: developer/prerequisites.md
      - Software Delivery Machine: developer/sdm.md
      - SDM Project: developer/sdm-project.md
      - Running SDMs: developer/run.md
      - Creating Projects: developer/create.md
      - Editing Projects: developer/edit.md
      - Inspecting Projects: developer/inspect.md
      - Commands: developer/commands.md
      - Events: developer/events.md
      - Slack Messages: developer/slack.md
      - GraphQL: developer/graphql.md
  - Support: support.md
