site_name: Atomist Documentation
site_description: Atomist Documentation
site_author: The Atomist Team
repo_name: GitHub
repo_url: https://github.com/atomist/docs
edit_uri: edit/master/docs/
copyright: "&copy; 2020 Atomist, Inc."
extra:
  main_site_url: https://atomist.com/
  social:
    - type: medium
      link: https://blog.atomist.com/
    - type: github
      link: https://github.com/atomist
    - type: twitter
      link: https://twitter.com/atomist
    - type: slack
      link: https://join.atomist.com/
theme:
  name: material
  favicon: "img/favicon.ico"
  logo: img/atomist-developer-docs-logo.png
  palette:
    primary: white
    accent: teal
  custom_dir: "theme"
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - smarty
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - toc:
      permalink: true
nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  # - How It Works: how-it-works.md
  # - Using Skills: using-skills.md
  - Integrations:
      - GitHub: integration/github.md
      - Slack: integration/slack.md
  #    - Docker Registries:
  #        - Docker Hub: integration/docker-hub.md
  #        - Google Container Registry: integration/gcr.md
  #    - Google Cloud Platform: integration/gcp.md
      - Kubernetes: integration/kubernetes.md
  # - Developing a Skill: skill/develop.md
  - SDM Guide:
      - Overview: developer/index.md
      - About the SDM:
          - Overview: developer/sdm.md
          - Architecture: developer/architecture.md
          - SDM Concepts: developer/sdm-concepts.md
          - SDM Components: developer/sdm-components.md
          - Team Mode: developer/team.md
          - Local Mode: developer/local.md
          - Command Line Interface: developer/cli.md
          - Security Model: developer/security.md
          - SDM Configuration: developer/config.md
          - Debugging an SDM: developer/sdm-debug.md
          - Deploying your SDM: developer/sdm-deploy.md
      - Using an SDM:
          - Introduction: user/index.md
          - Atomist web interface: user/dashboard.md
          - Source Control: user/github.md
          - Slack: user/slack.md
          - Built-in Chat Integrations: user/lifecycle.md
          - Integrating into Existing Tools: user/admin/integrations/supported-integrations.md
          - Workspace Administration:
              - Settings: user/admin/settings.md
              - Members: user/admin/members.md
      - SDM Development:
          - Prerequisites: developer/prerequisites.md
          - Setting up TypeScript in your IDE: developer/typescript.md
          - Events:
              - Event Listeners: developer/event.md
              - Code samples:
                  - "Example: Responding to repository creation": developer/respond-to-repo-creation.md
                  - "Example: Responding to issue creation": developer/respond-to-issue-creation.md
              - Custom Events: developer/custom-events.md
          - Goals:
              - Create Goals: developer/goal.md
              - Setting Goals: developer/set-goals.md
              - Goal Details: developer/goaldetails.md
              - Doing More with Goals: developer/goals-more.md
          - Builds:
              - Build Goal: developer/build.md
              - Integrations: user/ci.md
              - Generic Builder: developer/spawn-builder.md
          - Invocations: developer/invocation.md
          - Deploys: developer/deploy.md
          - Logging: developer/logging.md
          - Automation API: developer/command-http.md
          - Identifying a repository: developer/reporef.md
          - Custom GraphQL Queries: developer/graphql.md
          - Running External Commands: developer/spawn.md
          - Repo Targeting Parameters: developer/repo-targeting-params.md
          - HTTP Calls in an SDM: developer/http.md
          - Writing Push Tests: developer/push-test.md
          - Working with the AST: developer/astutils.md
          - Local mode quick start: developer/local-quick-start.md
          - Troubleshooting: developer/troubleshoot.md
      - What the SDM can do:
          - Commands: developer/commands.md
          - Code Inspections: developer/inspect.md
          - Code Transforms:
              - Transforms: developer/transform.md
              - Autofixes: developer/autofix.md
              - Project: developer/project.md
              - Path Expressions: developer/pxe.md
              - Using microgrammars: developer/parseutils.md
              - Modifying files: developer/projectutils.md
          - Chat Messages: developer/slack.md
          - Fingerprints: developer/fingerprint.md
          - Project Generators: developer/create.md
          - Delivery: developer/delivery.md
          - "Example: Putting it together": developer/putting-it-together.md
      - API Reference:
          - Packages Overview: developer/packages-overview.md
          - automation-client: https://atomist.github.io/automation-client/
          - sdm: https://atomist.github.io/sdm/
      - Tutorials:
          - Overview: developer/tutorials.md
          - Setting Up a Project Generator: developer/setting-up-generator.md
          - Writing your First Code Transform: developer/first-transform.md
          - Defining an SDM: developer/defining-sdm.md
          - Building your First Delivery: developer/first_delivery.md
          - Creating Container Goals: developer/container-goals.md
      - Extensions:
          - Extension Packs: pack/index.md
          - Build: pack/build.md
          - Changelog: pack/changelog.md
          - Checkstyle: pack/checkstyle.md
          - Cloud Foundry: pack/pcf.md
          - Docker: pack/docker.md
          - Kubernetes:
              - "Atomist & Kubernetes": pack/kubernetes/index.md
              - Kubernetes extension pack: pack/kubernetes/pack.md
              - Deploying applications: pack/kubernetes/deploy.md
              - GitOps: pack/kubernetes/sync.md
              - Installation: pack/kubernetes/install.md
          - Goal State: pack/goalstate.md
          - Issue: pack/issue.md
          - Lines of Code: pack/sloc.md
          - Markdown: pack/markdown.md
          - Node: pack/node.md
          - Sonarqube: pack/sonarqube.md
          - Java and Spring: pack/spring.md
  - Support: support.md
